### PR TITLE
Update README.md with Solar Games Mentorship

### PR DESCRIPTION
**Pull request by leonidaspir**
Added Solar Games PlayCanvas Mentorship

### CODE REVIEW

**Comment by yaustar** [comment]
Do you want add a small description on some areas you could mentor in? Eg shaders

**Comment by willeastcott** [comment]
I think that description is too long. I think the first sentence is sufficient. However, the thing that bothers me here is that everything else on the page is free but this is a premium/paid service that you're offering/promoting here. If we're going to allow that in the context of this list, I think it should at least be labelled as such. So maybe:

```
Premium PlayCanvas training and mentorship services.
```

**Comment by yaustar** [comment]
I was thinking of 

```
PlayCanvas mentorship for topics including performance optimization, rendering and shaders.
```

**Comment by leonidaspir** [comment]
Thanks guys for the suggestions! Let's keep it short as @willeastcott suggested.

**Review by willeastcott — APPROVED** [review]

**Pull request merged**
